package com.example.swasthyamitra.models

// A meal recommendation generated by Cloud Functions, stored in Firestore 'recommendations' collection
data class Recommendation(
    val documentId: String = "",
    val userId: String = "",
    val type: String = "",              // "Meal_Suggestion", "Macro_Alert", "Daily_Plan"
    val mealTime: String = "",          // "Breakfast", "Lunch", "Dinner", "Snack", "Anytime"
    val suggestedFoods: List<SuggestedFood> = emptyList(),
    val remainingCalories: Int = 0,     // how many calories user can still eat today
    val message: String = "",           // human-readable explanation
    val createdAt: Long = 0L,
    val status: String = "Pending"      // "Pending", "Accepted", "Dismissed", "Consumed"
)

// A single food suggestion within a Recommendation (one of possibly several alternatives)
data class SuggestedFood(
    val name: String = "",
    val calories: Int = 0,
    val protein: Double = 0.0,
    val carbs: Double = 0.0,
    val fat: Double = 0.0,
    val servingSize: String = "1 serving",
    val reason: String = ""  // why this food was suggested (e.g. "High protein, fits your goal")
)
